//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACE_Web_Based_Learning_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int ID { get; set; }
        public string CourseName { get; set; }
        public int CourseContent { get; set; }
    
        public virtual CourseContent CourseContent1 { get; set; }
    }
}
